### ISSUE TITLE
Virus Flag

### ISSUE THREAD

**Issue by dralik** [maxensas/xiletrade#1]
wind10 is flagging this as a trojan
"Trojan:Win32/Wacatac.C!ml"

**Comment by maxensas** [comment]
Hi, thanks for your contribution.
I'm using Windows 10 up to date with the latest patch for windows defender (the colander) and he detect nothing.
Xiletrade assembly use light protections against hacks, same kind of protections you find on malicious softwares. Here you can find a complete analysis from 72 different engines : https://www.virustotal.com/gui/file/c0662668394b7a3904c7688c85622c376c8638ab72810f8b9ba4e4d19bd24c50/detection
with 16 falses positives, take a closer look to get details (engine names). I completly understand your reluctance. 
This price checker isn't ready to be open source yet.
