### ISSUE TITLE
Affixes not showing while price checking (with CTRL-ALT-C)

### ISSUE THREAD

**Issue by Sagnax** [maxensas/xiletrade#12]
Affixes are not showing in the price check window

![image](https://user-images.githubusercontent.com/38547432/115295598-ed2edd00-a127-11eb-9991-44b0bdabf5bd.png)

![image](https://user-images.githubusercontent.com/38547432/115295691-06d02480-a128-11eb-96c2-228104388dd1.png)

**Comment by Sagnax** [comment]
okay, so this only happens with Alt key, setting the hotkey to Ctrl + something works fine.

**Comment by maxensas** [comment]
Yes, posted it yersterday on discord : 

For now, I advise you not to use the ALT key for keyboard shortcuts related to the price check feature. For Xiletrade software or any other until implementations came out.

**Content Update 3.14.0 -- Path of Exile: Ultimatum**
https://www.pathofexile.com/forum/view-thread/3079973

Section "User Interface Changes"
```
Copying an item's description with Ctrl + C now also copies the Item Class.
Pressing Ctrl + Alt + C now copies the Advanced Modifier Descriptions on an item.```

**Comment by maxensas** [comment]
Fixed : https://github.com/maxensas/xiletrade/releases/tag/1.5.0
