### ISSUE TITLE
Error message : RAR file is Damaged when extracting archive...

### ISSUE THREAD

**Issue by RevOlutix** [maxensas/xiletrade#16]
Can't download the file, tried on several machines, and get on all the same error!   The archive is either in unknown format or damaged

**Comment by LillieSatou** [comment]
Use 7Zip or latest WinRAR Beta.

**Comment by maxensas** [comment]
Hi, you can download 7Zip to extract all releases archives : https://www.7-zip.org/

After reconsidering the deployment method, all new version archives will be in the 7z file format. 
To make things easier, the process will be automated in a second step : making software updating all new files itself.

**Comment by maxensas** [comment]
see https://github.com/maxensas/xiletrade/releases/tag/1.5.2
