### ISSUE TITLE
Suggestion : Add /guild chat command

### ISSUE THREAD

**Issue by vertex101** [maxensas/xiletrade#21]
adding the `/guild` command into the list for shortcuts to get to ur guild hideout

**Comment by maxensas** [comment]
Sure, doable.

**Comment by maxensas** [comment]
![guild](https://user-images.githubusercontent.com/62154281/144431972-e9804c54-f869-4657-bd90-553746c7541d.png)

Added for 1.6.5 (wait release) :
https://github.com/maxensas/xiletrade/releases/tag/1.6.5
