### ISSUE TITLE
Error on requesting poewiki/poeninja information

### ISSUE THREAD

**Issue by BreadDain** [maxensas/xiletrade#23]
![изображение](https://user-images.githubusercontent.com/30041703/170517512-c8523ab3-266f-42ef-b695-ce7111c9a866.png)

Application throws multiple errors on first attempt to open wiki/ninja for any item, and Item parsing error repeatedly on any further requests. Tab in browser opens correctly per requested item.

**Comment by maxensas** [comment]
Hi BreadDain.

I will have a closer look on it soon.

Thanks for describing that issue, i will try to reproduce and fix it.

**Comment by maxensas** [comment]
Both errors fixed.
Opening wiki or ninja without price checking the item first now works correctly (features left out with previous multitasking enhancement).

Available next in 1.6.11

**Comment by maxensas** [comment]
Fixed in https://github.com/maxensas/xiletrade/releases/tag/1.7.0
