### ISSUE TITLE
Item evaluation in non-english does not work correctly

### ISSUE THREAD

**Issue by aadunin** [maxensas/xiletrade#29]
The item evaluation process does not display a particular piece of information
![Screenshot 2024-05-23 114220](https://github.com/maxensas/xiletrade/assets/49635297/b4da874b-3197-46c4-bca5-53b4f2992b5d)
![Screenshot 2024-05-23 120753](https://github.com/maxensas/xiletrade/assets/49635297/66903f45-72a3-4344-8300-d02cb6c1edc1)
![Screenshot 2024-05-23 120823](https://github.com/maxensas/xiletrade/assets/49635297/6b33435e-b945-4b8a-96b6-bf0a2db482ea)
![Screenshot 2024-05-23 120839](https://github.com/maxensas/xiletrade/assets/49635297/d2522cd2-d7b3-4d9b-ab69-8be2e4ed4b75)
![Screenshot 2024-05-23 120901](https://github.com/maxensas/xiletrade/assets/49635297/b65d59f9-4882-4571-b6bc-140291495af4)
![Screenshot 2024-05-23 120926](https://github.com/maxensas/xiletrade/assets/49635297/b5ee8ab1-4975-4aac-ad91-e6445c4135a3)

**Comment by maxensas** [comment]
Do not hesitate to post CTRL + ALT + C iem info description as well for each item. It really helps.

**Comment by aadunin** [comment]
Thanks for the reply, I will wait for the fix, I wish you success in developing the app!

**Comment by maxensas** [comment]
I am currently testing the software on non-English versions and indeed it does not work properly in Russian. Tested on unique items (request format issue) I will try to fix it for next release.

**Comment by maxensas** [comment]
This does not come from Xiletrade but when copying item info description and not just related to russian.
https://www.pathofexile.com/forum/view-thread/3560899

**Comment by aadunin** [comment]
Michaël, thank you for the work you have done, success in developing the app and have a good day!
