### ISSUE TITLE
Add Trade gateway selection - Will help Korean and Taiwanese players.

### ISSUE THREAD

**Issue by trost4497** [maxensas/xiletrade#37]
First of all, I would like to thank you for distributing this program for free.
It's very easy to use, but I have one suggestion.
Currently, the Korean exchange server is so slow that it is difficult to use.
Therefore, it is very difficult to use the function that moves to the browser after searching for an item.
I would be very grateful if you could update the settings so that you can be moved to the exchange site of the desired country.
thank you for your efforts

**Comment by maxensas** [comment]
Ok i understand the need. 
I tried to used Kakao in the past with POE1 to see how it works but i don't think we can use it as a non-Korean citizen so I didn't go any further.
Technically, it's seems to be very easy with this app. I will look at this tomorrow, this could also help Taiwaneses.

**Comment by messnoTrace** [comment]
Hello author, I found a bug, the current version of poe2, there is no traditional Chinese server, so I fork this project before and make my own modification, now I see you add a getway option, I found in the process of testing, when the language environment uses traditional Chinese, api uses us environment, there will be problems. Search API should be `https://www.pathofexile.com/api/trade2/search/poe2/Standard` instead of https://www.pathofexile.com/api/trade2/search/poe2 /標準模式    alliance this way

**Comment by maxensas** [comment]
Ok, I'll look into that today, thanks for the info

**Comment by messnoTrace** [comment]
Similarly, there is another problem, when my PC uses the traditional language environment, the copied item information is also traditional, so when requesting the English environment API, the parameters passed should be the need to convert the traditional to the English environment

**Comment by maxensas** [comment]
Good point, i saw this with unit tests, fix added in master branch : https://github.com/maxensas/xiletrade/commit/e97eb4a4a21437b58ca54dc97892b116d738ef0d

It now works fine for both Korean and Traditional Chinese clients that use other specific gateway. 
You can also use the Japanese Gateway (JP) and not US if it suits you better in terms of response time for requests.

Will be deployed next release.

![TradChinese](https://github.com/user-attachments/assets/2bad5b05-9aba-4bd5-a04e-11bba0f743cc)

**Comment by maxensas** [comment]
Release in https://github.com/maxensas/xiletrade/releases/tag/1.10.1
